import React, { useState, useEffect } from 'react';
import io from 'socket.io-client';
import {
  Box,
  Button,
  TextField,
  Typography,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  Avatar,
  Chip,
  CircularProgress,
  Container,
  Grid,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from '@mui/material';

const SOCKET_URL = process.env.REACT_APP_SOCKET_URL || 'http://localhost:3001';

function App() {
  const [socket, setSocket] = useState(null);
  const [agents, setAgents] = useState([]);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [tokenUsage, setTokenUsage] = useState({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedAgentId, setSelectedAgentId] = useState(null); // For prompting
  const [promptValue, setPromptValue] = useState('');
  const [token, setToken] = useState(''); // JWT token for authentication

  useEffect(() => {
    if (!token) {
      // No token, do not connect
      return;
    }

    const socketInstance = io(SOCKET_URL, {
      auth: {
        token: token
      }
    });

    socketInstance.on('connect', () => {
      console.log('Connected to server');
      setLoading(false);
    });

    socketInstance.on('connect_error', (err) => {
      console.error('Connection error:', err);
      setError(err.message);
      setLoading(false);
    });

    socketInstance.on('agents-list', (agentList) => {
      setAgents(agentList);
    });

    socketInstance.on('agent-joined', (agent) => {
      setAgents(prev => [...prev, agent]);
    });

    socketInstance.on('agent-left', ({ userId, username }) => {
      setAgents(prev => prev.filter(agent => agent.userId !== userId));
    });

    socketInstance.on('receive-message', (msg) => {
      setMessages(prev => [...prev, msg]);
    });

    socketInstance.on('agent-token-update', ({ agentId, tokenUsage: usage }) => {
      setTokenUsage(prev => ({
        ...prev,
        [agentId]: usage
      }));
    });

    return () => {
      socketInstance.disconnect();
    };
  }, [token]);

  const sendChatMessage = () => {
    if (!inputValue.trim()) return;
    socket.emit('send-message', {
      message: inputValue
    });
    setInputValue('');
  };

  const sendPrompt = () => {
    if (!promptValue.trim()) return;
    const targetId = selectedAgentId || undefined; // undefined means broadcast
    socket.emit('send-message', {
      targetId,
      message: promptValue,
      isPrompt: true
    });
    setPromptValue('');
  };

  if (loading) {
    return (
      <Container maxWidth="sm" sx={{ mt: 4 }}>
        <Typography variant="h4" align="center">
          Agent Dashboard
        </Typography>
        <CircularProgress />
      </Container>
    );
  }

  if (error) {
    return (
      <Container maxWidth="sm" sx={{ mt: 4 }}>
        <Typography color="error" align="center">
          Connection error: {error}
        </Typography>
      </Container>
    );
  }

  // If no token, show token input
  if (!token) {
    return (
      <Container maxWidth="sm" sx={{ mt: 4 }}>
        <Typography variant="h4" align="center">
          Agent Dashboard
        </Typography>
        <TextField
          label="JWT Token"
          value={token}
          onChange={(e) => setToken(e.target.value)}
          fullWidth
          sx={{ mt: 2 }}
          InputLabelProps={{
            shrink: true,
          }}
          helperText="Enter your JWT token to connect to the server"
        />
        <Button variant="contained" onClick={() => setToken(token.trim())} disabled={!token.trim()}>
          Connect
        </Button>
        <Typography variant="caption" align="center" sx={{ mt: 2 }}>
          For testing, you can use a token generated by your authentication system.
        </Typography>
      </Container>
    );
  }

  return (
    <>
      <Box sx={{ display: 'flex', height: '100vh' }}>
        {/* Agents Sidebar */}
        <Box sx={{ width: 250, borderRight: 1, p: 2, backgroundColor: '#fff' }}>
          <Typography variant="h6" gutterBottom>
            Connected Agents
          </Typography>
          <List>
            {agents.map(agent => (
              <ListItem key={agent.userId} sx={{ mb: 1 }}>
                <ListItemAvatar>
                  <Avatar>{agent.username.charAt(0).toUpperCase()}</Avatar>
                </ListItemAvatar>
                <ListItemText
                  primary={agent.username}
                  secondary={agent.type}
                />
                <Chip
                  label={`Tokens: ${tokenUsage[agent.userId] || 0}`}
                  size="small"
                  sx={{ ml: 1 }}
                />
              </ListItem>
            ))}
          </List>
        </Box>

        {/* Chat and Prompt Main */}
        <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', p: 2 }}>
          <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
            {/* Chat Area */}
            <Box sx={{ flex: 1, overflow: 'auto', mb: 2, p: 2, backgroundColor: '#fff', borderRadius: 1 }}>
              <Typography variant="h5" gutterBottom>
                Chat
              </Typography>
              <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column-reverse' }}>
                {messages.map((msg, index) => {
                  const isPrompt = msg.isPrompt;
                  return (
                    <Box key={index} sx={{ mb: 1, p: 1, borderRadius: 1, backgroundColor: isPrompt ? '#fff3e0' : '#e3f2fd', maxWidth: '80%' }}>
                      <Typography variant="body1">
                        <strong>{msg.fromUsername || 'Agent'}:</strong> {msg.message}
                        {isPrompt && ' (PROMPT)'}
                      </Typography>
                    </Box>
                  );
                })}
              </Box>
            </Box>
            <Box sx={{ display: 'flex' }}>
              <TextField
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                placeholder="Type a chat message..."
                fullWidth
                sx={{ mr: 2 }}
                onKeyPress={(e) => e.key === 'Enter' && sendChatMessage()}
              />
              <Button variant="contained" onClick={sendChatMessage}>
                Send Chat
              </Button>
            </Box>
          </Box>

          {/* Prompt Area */}
          <Box sx={{ mt: 2, p: 2, backgroundColor: '#fff', borderRadius: 1 }}>
            <Typography variant="h5" gutterBottom>
              Send Prompt to Agent
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', mb: 2 }}>
              <FormControl fullWidth sx={{ mb: 1 }}>
                <InputLabel id="agent-label">Select Agent</InputLabel>
                <Select
                  labelId="agent-label"
                  value={selectedAgentId}
                  label="Select Agent"
                  onChange={(e) => setSelectedAgentId(e.target.value)}
                  sx={{ width: '100%' }}
                  emptyValue={undefined}
                >
                  <MenuItem value={undefined}>
                    <em>All Agents (Broadcast)</em>
                  </MenuItem>
                  {agents.map(agent => (
                    <MenuItem key={agent.userId} value={agent.userId}>
                      {agent.username} ({agent.type})
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
              <TextField
                value={promptValue}
                onChange={(e) => setPromptValue(e.target.value)}
                placeholder="Enter prompt..."
                fullWidth
                sx={{ mb: 1 }}
                onKeyPress={(e) => e.key === 'Enter' && sendPrompt()}
              />
              <Button variant="contained" color="secondary" onClick={sendPrompt}>
                Send Prompt
              </Button>
            </Box>
          </Box>
        </Box>
      </Box>
    </>
  );
}

export default App;